version: '3'
services:
  app:
    image: user-management-api
    build:
      context: .
    ports:
      - "8081:8080"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/dist
    environment:
      - NODE_ENV=production
